name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build for GitHub Pages
        run: |
          npm run build:gh

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          personal_token: ${{ env.PERSONAL_TOKEN }}
          publish_dir: ./dist
